'use strict';
const names=['仕事と勤務地','給与','勤務時間と休日','契約と試用期間','待遇と応募','原稿の確認'];
const heads=['どんな仕事の募集ですか？','給与を教えてください','いつ働く仕事ですか？','契約と試用期間について','待遇と応募先を確認しましょう','求人原稿を確認しましょう'];
const leads=['まずは、仕事の内容と働く場所から。箇条書きでも大丈夫です。','基本給と、全員に支給する金額を分けて入力します。','決まった時間と、相談できる時間帯を区別します。','回答に合わせて、必要な質問だけ表示します。','すでに入力した内容は、もう一度入力する必要はありません。','不足している内容は、該当する画面へ戻って確認できます。'];
const state={step:0,values:{},allowances:[{}],shifts:[{}],examples:[{}]};
const v=state.values; const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const val=k=>v[k]??''; const yes=k=>val(k)==='yes'; const yen=x=>Number(x).toLocaleString('ja-JP')+'円';
function field(k,label,type='text',hint='',attrs=''){return `<label class="field"><span>${esc(label)}</span><input id="${k}" data-key="${k}" type="${type}" value="${esc(val(k))}" ${type==='number'?'min="0" step="any"':''} ${attrs}>${hint?`<small class="hint">${esc(hint)}</small>`:''}</label>`;}
function area(k,label){return `<label class="field"><span>${esc(label)}</span><textarea id="${k}" data-key="${k}">${esc(val(k))}</textarea></label>${typeof examples !== 'undefined' && examples[k] ? `<button type="button" class="secondary" data-example="${k}">記入例を見る</button>` : ''}`;}
function select(k,label,opts){return `<label class="field"><span>${esc(label)}</span><select id="${k}" data-key="${k}"><option value="">選んでください</option>${opts.map(([a,b])=>`<option value="${a}" ${val(k)===a?'selected':''}>${esc(b)}</option>`).join('')}</select></label>`;}
function choices(k,label,opts=[['no','なし'],['yes','あり']]){return `<div role="group" aria-label="${esc(label)}"><h3>${esc(label)}</h3><div class="choices">${opts.map(([a,b])=>`<label class="choice"><input type="radio" data-key="${k}" name="${k}" value="${a}" ${val(k)===a?'checked':''}>${esc(b)}</label>`).join('')}</div></div>`;}
function check(k,label){return `<label class="check"><input type="checkbox" id="${k}" data-key="${k}" ${v[k]?'checked':''}>${esc(label)}</label>`;}
const card=(title,body)=>`<section class="card"><h2>${title}</h2>${body}</section>`;
const branch=body=>`<div class="branch">${body}</div>`;const row=body=>`<div class="row">${body}</div>`;
function optional(k,title,body){return `<section class="card"><details data-detail="${k}" ${v[k]?'open':''}><summary>${title}</summary>${body}</details></section>`;}
const units=[['month','月給'],['hour','時給'],['day','日給']];const unitName=()=>({month:'月給',hour:'時給',day:'日給'}[val('unit')]||'給与');
function reportedSalary(){const min=Number(val('reported')),max=Number(val('reportedMax'));if(!val('unit')||!val('totalFormat')||!Number.isSafeInteger(min)||min<=0)return '';let text=yen(min);if(val('totalFormat')==='range'){if(!Number.isSafeInteger(max)||max<min)return '総支給額の上限は下限以上で入力してください';text=min.toLocaleString('ja-JP')+'～'+yen(max);}if(val('totalFormat')==='above')text+='～';return unitName()+' '+text;}
function salary(){
 if(v.totalOnly){const t=reportedSalary();return {ready:false,label:t||'総支給額の表記と金額を入力してください',reason:'総額入力の表示です。内訳・法令の確認は行っていません。'};}
 if(!val('unit')||val('base')===''||!['yes','no'].includes(val('uniform'))||!['yes','no'].includes(val('fixed')))return {ready:false,label:'内訳を入力すると合計が表示されます',reason:'未回答を「なし」や0円として計算しません。'};
 let total=Number(val('base'));if(!Number.isSafeInteger(total)||total<=0)return {ready:false,label:'基本給を確認してください',reason:'金額は1円以上の整数で入力してください。'};
 if(yes('uniform')){for(const a of state.allowances){if(!a.name||a.amount===''||a.amount===undefined||!Number.isSafeInteger(Number(a.amount))||Number(a.amount)<0)return {ready:false,label:'一律手当の入力を確認してください',reason:'手当名と同じ支給単位の金額が必要です。'};total+=Number(a.amount);}}
 if(yes('fixed')){if(val('fixedAmount')===''||val('fixedHours')===''||Number(val('fixedHours'))<=0||!Number.isSafeInteger(Number(val('fixedAmount')))||Number(val('fixedAmount'))<=0)return {ready:false,label:'固定残業代を確認してください',reason:'金額と何時間分かを入力してください。'};total+=Number(val('fixedAmount'));}
 return {ready:true,total,label:unitName()+' '+yen(total)+(v.salaryAbove?'以上':''),reason:'基本給 ＋ 一律手当 ＋ 固定残業代（同じ支給単位）'};
}
function totalBox(){const s=salary();return `<div class="total" aria-live="polite"><small>全員に支給される給与総額</small><output id="salary-total">${esc(s.label)}</output><p id="salary-reason">${esc(s.reason)}</p></div>`;}
function allowanceRows(){return state.allowances.map((a,i)=>`<div class="repeat">${row(`<label class="field"><span>手当名</span><input aria-label="一律手当${i+1}の名前" data-list="allowances" data-index="${i}" data-prop="name" value="${esc(a.name)}"></label><label class="field"><span>金額（円・基本給と同じ単位）</span><input aria-label="一律手当${i+1}の金額" type="number" min="0" step="1" data-list="allowances" data-index="${i}" data-prop="amount" value="${esc(a.amount)}"></label>`)}${state.allowances.length>1?`<button class="link" type="button" data-remove="allowances" data-index="${i}">この手当を削除</button>`:''}</div>`).join('')+'<button class="secondary" type="button" data-add="allowances">手当を追加</button>';}
function shiftRows(list){return state[list].map((a,i)=>`<div class="repeat"><h3>${list==='examples'?'勤務例':'シフト'} ${i+1}</h3><div class="row three">${['start','end','break'].map((p,j)=>`<label class="field"><span>${['開始時刻','終了時刻','休憩（分）'][j]}</span><input aria-label="${list==='examples'?'勤務例':'シフト'}${i+1}${['開始時刻','終了時刻','休憩'][j]}" type="${p==='break'?'number':'time'}" ${p==='break'?'min="0" step="1"':''} data-list="${list}" data-index="${i}" data-prop="${p}" value="${esc(a[p])}"></label>`).join('')}</div><label class="check"><input type="checkbox" data-list="${list}" data-index="${i}" data-prop="overnight" ${a.overnight?'checked':''}>終了は翌日</label>${state[list].length>1?`<button type="button" class="link" data-remove="${list}" data-index="${i}">この時間を削除</button>`:''}</div>`).join('')+`<button type="button" class="secondary" data-add="${list}">${list==='examples'?'勤務例':'シフト'}を追加</button>`;}
function clock(x){if(!/^\d{2}:\d{2}$/.test(x||''))return null;let[h,m]=x.split(':').map(Number);return h*60+m;}
function hasNight(){let a=[];if(val('timeMode')==='fixed')a=[{start:val('start'),end:val('end'),overnight:v.overnight}];if(val('timeMode')==='shifts')a=state.shifts;if(val('timeMode')==='window')a=[{start:val('windowStart'),end:val('windowEnd'),overnight:v.windowOvernight},...(v.showExamples?state.examples:[])];return a.some(x=>{let s=clock(x.start),e=clock(x.end);if(s===null||e===null)return false;if(x.overnight)e+=1440;return e>s&&(s<300||e>1320);});}
function workHours(){let s=clock(val('start')),e=clock(val('end'));if(s===null||e===null||val('break')==='')return '';if(v.overnight)e+=1440;const n=e-s-Number(val('break'));return n>0?`実働 ${(n/60).toLocaleString('ja-JP',{maximumFractionDigits:2})} 時間`:'時刻・翌日・休憩を確認してください';}
function screens(){switch(state.step){
case 0:return card('仕事の名前',field('jobTitle','募集する仕事の名前')+select('occupation','仕事の種類',[['office','事務'],['service','接客・飲食'],['technical','技術・施工'],['care','介護・福祉'],['other','その他']]))+card('雇用形態',select('employment','雇用形態',[['regular','正社員'],['part','アルバイト・パート'],['contract','契約社員'],['other','その他']]))+card('お願いする仕事',area('duties','主な作業・扱うもの・仕事の進め方'))+optional('qualOpen','＋ 応募に必要な資格・経験を追加',area('required','応募資格・対象（取込原文。必須・歓迎は内容を確認）')+area('welcome','あれば歓迎する資格・経験'))+card('働く場所',field('workplace','職場・店舗の名前（任意）')+field('address','働く場所の住所')+choices('fieldWork','訪問先・現場などでも働きますか？')+(yes('fieldWork')?branch(area('workArea','訪問先・担当するエリア')):''))+optional('changesOpen','＋ 採用後に変わる可能性がある場合',choices('dutyChange','仕事内容',[['no','変わらない'],['yes','変わる']])+(yes('dutyChange')?branch(area('dutyScope','どの仕事まで変わりますか？')):'')+choices('placeChange','働く場所',[['no','変わらない'],['yes','変わる']])+(yes('placeChange')?branch(area('placeScope','どの場所まで変わりますか？')):''));
case 1:return card('基本給',select('unit','支払い方',units)+check('totalOnly','総額で記載する')+(!v.totalOnly?check('salaryAbove','この金額以上で募集する（例：200,000円以上）'):'')+(v.totalOnly?branch(select('totalFormat','総支給額の表記',[['exact','金額を指定：200,000円'],['range','幅を指定：200,000～250,000円'],['above','下限を指定：200,000円～（以上）']])+field('reported',val('totalFormat')==='range'?'総支給額の下限(円)':'総支給額(円)','number')+(val('totalFormat')==='range'?field('reportedMax','総支給額の上限(円)','number'):'')+'<p class="warning">内訳は後で確認してください。ここでは総額から基本給を推定しません。</p>'):field('base','基本給はいくらですか？（円）','number','一律手当・固定残業代を除いた金額です。','step="1"')))+card('全員に毎回支給する手当',choices('uniform','一律支給手当はありますか？')+(yes('uniform')?branch(allowanceRows()):''))+card('固定残業代',choices('fixed','固定残業代は含まれていますか？')+(yes('fixed')?branch(row(field('fixedAmount','固定残業代（円）','number')+field('fixedHours','何時間分ですか？','number'))+select('fixedScope','対象となる残業',[['normal','通常の時間外労働'],['combined','深夜・休日も含む']])+(val('fixedScope')==='combined'?area('fixedDetails','深夜・休日分の内訳・時間'):'')+'<p class="hint">基本給と同じ支給単位の金額・時間を入力してください。</p><p class="warning">固定残業時間を超過した分は別途全額支給、と原稿に表示します。</p>'+choices('excess','実際の支払い条件と一致しますか？',[['yes','一致する'],['unknown','確認が必要']])):'')+totalBox())+card('給与の上限',choices('showUpper','上限額も表示しますか？',[['no','表示しない'],['yes','表示する']])+(yes('showUpper')?branch(field('upperBase','上限時の基本給（変わる場合だけ）','number')+area('upperComponents','給与がいちばん高くなる場合、手当や固定残業代はいくらですか？')+'<p class="hint">例：一律資格手当20,000円、固定残業代30,000円（20時間分）。最低額と同じなら「変更なし」と記入してください。</p>'+field('upperTotal','給与総額はいくらまで支給しますか？（円）','number','基本給・一律手当・固定残業代を合わせた金額です。例：基本給250,000円＋手当20,000円＋固定残業代30,000円＝300,000円。交通費や条件付き手当は含めません。')+area('upperBasis','どんな人・条件なら、この最高額になりますか？')+'<p class="hint">このPoCでは上限内訳の自動計算を行いません。別々の最大額を足し合わせないでください。</p>'):''))+card('交通費・条件付き手当など',choices('additional','ほかに支給する手当はありますか？')+(yes('additional')?branch(area('additionalText','手当名・金額や上限・支給条件')):'')+'<p class="hint">条件付き手当や実費交通費は、上の給与総額には加えません。</p>');
case 2:{let mode=val('timeMode');let timing='';if(mode==='fixed')timing=branch(row(field('start','開始時刻','time')+field('end','終了時刻','time'))+check('overnight','終了は翌日')+field('break','休憩は何分ですか？','number')+`<p id="hours" class="hint">${esc(workHours())}</p>`);if(mode==='shifts')timing=branch(shiftRows('shifts'));if(mode==='window')timing=branch(row(field('windowStart','勤務できる時間帯の始まり','time')+field('windowEnd','勤務できる時間帯の終わり','time'))+check('windowOvernight','時間帯の終わりは翌日')+row(field('minHours','1日最低何時間ですか？','number')+field('maxHours','1日最大何時間ですか？（分かる場合）','number'))+area('windowBreak','長く働く日の勤務時間と休憩')+check('showExamples','勤務例を追加する')+(v.showExamples?shiftRows('examples'):'')+'<p class="hint">この時間帯や勤務例から実働時間は計算しません。</p>');if(mode==='other')timing=branch(area('otherTime','勤務時間の決め方・時間を教えてください'));return card('働く時間',select('timeMode','時間はどのように決まりますか？',[['fixed','毎回同じ時間'],['shifts','決まったシフト'],['window','時間帯の中で相談'],['other','その他']])+timing+(hasNight()?branch('<p class="warning">夜間の時間帯が含まれています。</p>'+choices('daytime','日中の勤務も募集しますか？')+area('minorHours','18歳未満が働ける時間帯（いない場合も記載）')+'<p class="hint">夜間だけの条件を、求人全体の年齢条件にはしません。</p>'):''))+card('勤務日数と休日',row(select('daysUnit','日数の数え方',[['week','週'],['month','月平均']])+field('daysMin','勤務日数（日）','number'))+check('daysRange','勤務日数に幅がある')+(v.daysRange?field('daysMax','最多の勤務日数（日）','number'):'')+select('holidayType','休日の決まり方',[['fixed','曜日固定'],['shift','シフトによる'],['other','その他']])+area('holidays','休日・休暇の内容'))+card('実際の残業',choices('overtime','実際に残業はありますか？')+(yes('overtime')?branch(field('otMin','月平均の残業時間','number')+check('otRange','残業時間に幅がある')+(v.otRange?field('otMax','月平均の上限時間','number'):'')):'')+'<p class="hint">固定残業代の時間とは別の、実際の残業量です。</p>');}
case 3:return card('契約期間',choices('contract','契約の終わりは決まっていますか？',[['no','決まっていない'],['yes','決まっている']])+(yes('contract')?branch(field('contractPeriod','期間または終了日')+select('renewal','契約を更新しますか？',[['no','更新しない'],['auto','自動更新'],['conditional','条件で判断']])+(['auto','conditional'].includes(val('renewal'))?area('renewalTerms','更新条件')+choices('renewalCap','更新回数・合計期間の上限はありますか？')+(yes('renewalCap')?field('renewalLimit','更新の上限'): ''):'')) :''))+card('試用期間',choices('trial','試用期間はありますか？')+(yes('trial')?branch(row(field('trialMin','試用期間の長さ','number')+select('trialUnit','期間の単位',[['month','か月'],['week','週間'],['day','日']]))+check('trialRange','期間に幅がある')+(v.trialRange?field('trialMax','最長の期間','number')+area('trialBasis','期間は何によって決まりますか？'):'')+choices('trialDiff','本採用と条件は同じですか？',[['same','同じ'],['different','一部違う']])+(val('trialDiff')==='different'?branch('<p class="hint">違う項目だけ選んで入力してください。</p>'+check('trialSalaryDiff','給与が違う')+(v.trialSalaryDiff?select('trialSalaryUnit','試用期間の支払い方',units)+field('trialBase','試用期間の基本給（円）','number')+area('trialAllowances','試用中の一律手当・固定残業代の適用と金額')+'<p class="hint">支払い方が変わっても、本採用の月額手当をそのまま引き継ぎません。</p>':'')+check('trialHoursDiff','勤務時間が違う')+(v.trialHoursDiff?area('trialHours','試用中の勤務時間・休憩'):'')+check('trialBenefitsDiff','待遇などが違う')+(v.trialBenefitsDiff?area('trialBenefits','試用中だけ変わる待遇・その他の条件'):'')):'')):''));
case 4:return card('会社・職場の情報',field('company','正式な募集企業名')+field('companyAddress','企業の所在地')+field('contact','公開する問い合わせ先','text','電話番号またはメールアドレス')+area('insurance','加入保険と、対象となる条件')+select('smoking','この職場の喫煙対策',[['none','敷地内禁煙'],['indoor','屋内禁煙'],['area','喫煙専用室あり'],['other','その他']])+(['other','area'].includes(val('smoking'))?area('smokingDetails','喫煙対策の詳細'):'')+'<p class="hint">このPoCには登録済みの会社情報がありません。</p>')+card('年齢条件',choices('age','求人全体に年齢条件はありますか？')+(yes('age')?branch(field('ageRange','対象となる年齢')+area('ageReason','仕事上の理由')):'')+ (hasNight()?'<p class="hint">夜間に関する回答は勤務時間の画面で保持しています。</p>':'') )+optional('extrasOpen','＋ 待遇・職場紹介・選考説明を追加',area('benefits','待遇の補足')+area('workIntro','職場紹介')+area('selection','選考について'))+card('応募方法',select('applyMethod','応募方法（試作用の選択肢）',[['email','メール'],['phone','電話'],['url','外部の応募ページ']])+choices('sameContact','応募先は問い合わせ先と同じですか？',[['yes','同じ'],['no','別の受付先']])+(val('sameContact')==='no'?field('applyTarget','応募の受付先'):yes('sameContact')?`<p class="hint">応募先：${esc(val('contact')||'問い合わせ先が未入力です')}</p>`:'')+'<p class="hint">応募は送信しません。採用する応募方法は別途検討中です。</p>');
case 5:return review();}}
function scheduleText(){switch(val('timeMode')){case 'fixed':return `${val('start')||'未入力'}〜${v.overnight?'翌':''}${val('end')||'未入力'}／休憩 ${val('break')||'未入力'}分\n${workHours()}`;case 'shifts':return state.shifts.map(x=>`${x.start||'未入力'}〜${x.overnight?'翌':''}${x.end||'未入力'}／休憩 ${x.break??'未入力'}分`).join('\n');case 'window':return `勤務可能な時間帯：${val('windowStart')||'未入力'}〜${v.windowOvernight?'翌':''}${val('windowEnd')||'未入力'}\n1日最低 ${val('minHours')||'未入力'}時間${val('maxHours')?'、最大 '+val('maxHours')+'時間':''}\n${val('windowBreak')}${v.showExamples?'\n勤務例：\n'+state.examples.map(x=>`${x.start||'未入力'}〜${x.overnight?'翌':''}${x.end||'未入力'}`).join('\n'):''}`;default:return val('otherTime')||'未入力';}}
function salaryText(){let s=salary();let t=s.ready?s.label:`${unitName()}：${v.totalOnly?reportedSalary()||'総支給額未入力':s.label}`;if(!v.totalOnly){t+=`\n基本給：${val('base')?yen(val('base')):'未入力'}`;if(yes('uniform'))t+='\n'+state.allowances.map(a=>`${a.name||'手当名未入力'}：${a.amount!==undefined&&a.amount!==''?yen(a.amount):'金額未入力'}`).join('\n');if(yes('fixed'))t+=`\n固定残業代：${val('fixedAmount')?yen(val('fixedAmount')):'未入力'}（${val('fixedHours')||'未入力'}時間分）\n${val('excess')==='yes'?'超過分は別途全額支給':'超過分の支払い条件は確認待ち'}`;}if(yes('showUpper'))t+=`\n上限申告値：${val('upperTotal')?yen(val('upperTotal')):'未入力'}（内訳対応の評価は未実装）`;if(yes('additional'))t+='\nその他手当：'+(val('additionalText')||'未入力');return t;}
function trialText(){if(val('trial')==='no')return '試用期間なし';if(!yes('trial'))return '未回答・確認待ち';let t=`${val('trialMin')||'未入力'}${v.trialRange?'〜'+(val('trialMax')||'未入力'):''}${{month:'か月',week:'週間',day:'日'}[val('trialUnit')]||'（単位未入力）'}`;if(v.trialRange)t+='\n期間の決め方：'+(val('trialBasis')||'未入力');if(val('trialDiff')==='same')return t+'／本採用と同条件';if(val('trialDiff')!=='different')return t+'／条件は確認待ち';if(v.trialSalaryDiff)t+=`\n試用給与：${{month:'月給',hour:'時給',day:'日給'}[val('trialSalaryUnit')]||'単位未入力'} ${val('trialBase')?yen(val('trialBase')):'金額未入力'}\n手当・固定残業：${val('trialAllowances')||'適用未確認'}`;if(v.trialHoursDiff)t+='\n勤務時間：'+(val('trialHours')||'未入力');if(v.trialBenefitsDiff)t+='\n待遇等：'+(val('trialBenefits')||'未入力');return t;}
function issues(){let list=[];const need=(k,label,step)=>{if(val(k)===''||val(k)==='unknown')list.push({label,step});};[['jobTitle','仕事の名前',0],['occupation','仕事の種類',0],['employment','雇用形態',0],['duties','仕事内容',0],['address','勤務地',0],['fieldWork','訪問・現場勤務の有無',0],['dutyChange','仕事内容の変更',0],['placeChange','勤務地の変更',0],['unit','給与の支払い方',1],['showUpper','上限の表示',1],['additional','その他手当の有無',1],['timeMode','勤務時間の決め方',2],['daysUnit','勤務日数の単位',2],['daysMin','勤務日数',2],['holidayType','休日の決まり方',2],['holidays','休日の内容',2],['overtime','残業の有無',2],['contract','契約期限',3],['trial','試用期間',3],['company','募集企業名',4],['companyAddress','企業の所在地',4],['contact','問い合わせ先',4],['insurance','加入保険',4],['smoking','喫煙対策',4],['age','求人全体の年齢条件',4],['applyMethod','応募方法',4],['sameContact','応募先',4]].forEach(a=>need(...a));
if(!salary().ready)list.push({label:v.totalOnly?'総支給額の内訳確認（このPoCでは未判定）':salary().label,step:1});
if(yes('fieldWork'))need('workArea','訪問・現場のエリア',0);if(yes('dutyChange'))need('dutyScope','仕事内容の変更範囲',0);if(yes('placeChange'))need('placeScope','勤務地の変更範囲',0);
if(yes('fixed')){need('fixedScope','固定残業の対象',1);need('excess','超過分の支払い条件',1);if(val('fixedScope')==='combined')need('fixedDetails','深夜・休日分の内訳',1);}
if(yes('additional'))need('additionalText','その他手当の条件',1);if(yes('showUpper')){need('upperTotal','給与の上限申告値',1);need('upperBasis','上限給与の適用条件',1);list.push({label:'上限内訳の対応はこのPoCでは判定しません',step:1});}
if(val('timeMode')==='fixed'){need('start','開始時刻',2);need('end','終了時刻',2);need('break','休憩',2);if(workHours().includes('確認'))list.push({label:workHours(),step:2});}if(val('timeMode')==='window'){['windowStart','windowEnd','minHours','windowBreak'].forEach((k,i)=>need(k,['勤務可能枠の開始','勤務可能枠の終了','1日の最低勤務時間','長い勤務日の休憩'][i],2));}if(val('timeMode')==='shifts'&&state.shifts.some(x=>!x.start||!x.end||x.break===undefined||x.break===''))list.push({label:'シフトの時刻・休憩',step:2});
if(hasNight()){need('daytime','日中の募集の有無',2);need('minorHours','18歳未満の勤務範囲',2);}if(yes('overtime'))need('otMin','月平均の残業時間',2);
if(yes('contract')){need('contractPeriod','契約期間',3);need('renewal','契約の更新',3);if(['auto','conditional'].includes(val('renewal'))){need('renewalTerms','更新条件',3);need('renewalCap','更新上限の有無',3);if(yes('renewalCap'))need('renewalLimit','更新の上限',3);}}
if(yes('trial')){need('trialMin','試用期間の長さ',3);need('trialUnit','試用期間の単位',3);need('trialDiff','試用期間の条件差',3);if(v.trialRange){need('trialMax','最長試用期間',3);need('trialBasis','試用期間の決定条件',3);}if(val('trialDiff')==='different'){if(!v.trialSalaryDiff&&!v.trialHoursDiff&&!v.trialBenefitsDiff)list.push({label:'試用中に変わる項目',step:3});if(v.trialSalaryDiff){need('trialSalaryUnit','試用の給与単位',3);need('trialBase','試用の基本給',3);need('trialAllowances','試用中の手当・固定残業の適用',3);}if(v.trialHoursDiff)need('trialHours','試用中の勤務時間',3);if(v.trialBenefitsDiff)need('trialBenefits','試用中の待遇',3);}}
if(yes('age')){need('ageRange','対象年齢',4);need('ageReason','年齢条件の理由',4);}if(val('sameContact')==='no')need('applyTarget','応募受付先',4);return list;}
function review(){const list=issues();let preview=[['仕事内容',val('duties')||'未入力',0],['給与',salaryText(),1],['勤務時間',scheduleText()+`\n勤務日数：${val('daysMin')||'未入力'}${v.daysRange?'〜'+(val('daysMax')||'未入力'):''}日／${val('daysUnit')==='week'?'週':val('daysUnit')==='month'?'月平均':'単位未入力'}\n残業：${val('overtime')==='no'?'なし':yes('overtime')?(val('otMin')||'未入力')+(v.otRange?'〜'+(val('otMax')||'未入力'):'')+'時間／月':'確認待ち'}`,2],['休日・休暇',val('holidays')||'未入力',2],['契約期間',val('contract')==='no'?'期間の定めなし':yes('contract')?(val('contractPeriod')||'未入力')+'\n更新：'+({no:'更新なし',auto:'自動更新',conditional:'条件で判断'}[val('renewal')]||'確認待ち')+'\n'+val('renewalTerms')+(yes('renewalCap')?'\n更新上限：'+val('renewalLimit'):''):'確認待ち',3],['待遇',`加入保険：${val('insurance')||'未入力'}\n喫煙対策：${{none:'敷地内禁煙',indoor:'屋内禁煙',area:'喫煙専用室あり',other:'その他'}[val('smoking')]||'確認待ち'} ${val('smokingDetails')}\n${val('benefits')}`,4],['試用期間',trialText(),3],['応募条件',`応募資格・対象：${val('required')||'未記載'}\n歓迎：${val('welcome')||'未記載'}\n年齢条件：${val('age')==='no'?'求人全体の制限なし':yes('age')?val('ageRange')+' '+val('ageReason'):'確認待ち'}${hasNight()?'\n夜間勤務・18歳未満の範囲：'+(val('minorHours')||'確認待ち'):''}`,0],['募集企業・勤務地・応募先',`${val('company')||'企業名未入力'}／${val('companyAddress')||'所在地未入力'}\n職場：${val('workplace')} ${val('address')||'勤務地未入力'}\n${yes('fieldWork')?'担当エリア：'+val('workArea')+'\n':''}仕事内容の変更：${val('dutyChange')==='no'?'なし':yes('dutyChange')?val('dutyScope'):'確認待ち'}\n勤務地の変更：${val('placeChange')==='no'?'なし':yes('placeChange')?val('placeScope'):'確認待ち'}\n問い合わせ：${val('contact')||'未入力'}\n応募先：${yes('sameContact')?val('contact'):val('sameContact')==='no'?val('applyTarget'):'確認待ち'}`,4]];
return card(esc(val('jobTitle')||'求人原稿のプレビュー'),`<div class="preview">${preview.map(([h,t,s])=>`<h3>${h}<button type="button" class="link" data-go="${s}">編集</button></h3><div>${esc(t)}</div>`).join('')}${val('workIntro')?'<h3>職場紹介</h3><div>'+esc(val('workIntro'))+'</div>':''}${val('selection')?'<h3>選考について</h3><div>'+esc(val('selection'))+'</div>':''}</div>`)+card(`入力・確認が残っている項目（${list.length}件）`,list.length?`<ul class="issue-list">${list.map(x=>`<li><button type="button" data-go="${x.step}"><span>${esc(x.label)}</span><span>確認する →</span></button></li>`).join('')}</ul>`:'<p>試作用の入力確認項目は埋まりました。法令・安全性の掲載判定は行っていません。</p>')+card('自動で補った表示','<p class="hint">給与総額、固定時間の実働、確認済みの超過分支給文。同条件の試用は本採用条件を参照します。</p>')+card('掲載期間を選ぶ',choices('period','掲載期間',[['7','7日'],['14','14日'],['21','21日'],['28','28日']])+'<p class="warning">期間の選択のみ体験できます。公開・掲載予約・期限処理は行いません。</p>');}
function render(focus=false){document.getElementById('steps').innerHTML=names.map((n,i)=>`<button type="button" class="step ${i===state.step?'active':''}" data-go="${i}" ${i===state.step?'aria-current="step"':''}><b>${String(i+1).padStart(2,'0')}</b>${n}</button>`).join('');document.getElementById('step-count').textContent=`STEP ${String(state.step+1).padStart(2,'0')} / 06`;document.getElementById('title').textContent=heads[state.step];document.getElementById('lead').textContent=leads[state.step];document.getElementById('form').innerHTML=screens();document.getElementById('back').disabled=state.step===0;document.getElementById('next').textContent=state.step===5?'確認体験を終える':'次へ';if(focus){document.getElementById('title').focus({preventScroll:true});window.scrollTo({top:0,behavior:'instant'});}document.querySelectorAll('details').forEach(d=>d.addEventListener('toggle',()=>v[d.dataset.detail]=d.open));}
function updateDerived(){if(state.step===1){const s=salary();const t=document.getElementById('salary-total');if(t)t.textContent=s.label;const r=document.getElementById('salary-reason');if(r)r.textContent=s.reason;}if(state.step===2){let h=document.getElementById('hours');if(h)h.textContent=workHours();}}
document.addEventListener('input',e=>{const t=e.target;if(t.dataset.key&& !['radio','checkbox'].includes(t.type)&&t.tagName!=='SELECT')v[t.dataset.key]=t.value;if(t.dataset.list)state[t.dataset.list][Number(t.dataset.index)][t.dataset.prop]=t.type==='checkbox'?t.checked:t.value;updateDerived();});
document.addEventListener('change',e=>{const t=e.target;const key=t.dataset.key;if(key==='unit'&&val('unit')&&val('unit')!==t.value){v.base='';v.fixedAmount='';v.fixedHours='';state.allowances.forEach(a=>a.amount='');}if(key)v[key]=t.type==='checkbox'?t.checked:t.value;if(t.dataset.list)state[t.dataset.list][Number(t.dataset.index)][t.dataset.prop]=t.type==='checkbox'?t.checked:t.value;if(!['radio','checkbox','time'].includes(t.type)&&t.tagName!=='SELECT'){updateDerived();return;}const cursor=key?`[data-key="${key}"]${t.type==='radio'?`[value="${t.value}"]`:''}`:t.dataset.list?`[data-list="${t.dataset.list}"][data-index="${t.dataset.index}"][data-prop="${t.dataset.prop}"]`:null;render();if(cursor&&t.type!=='time')document.querySelector(cursor)?.focus({preventScroll:true});});
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.example&&examples[b.dataset.example]){activeExample=b.dataset.example;const ex=examples[activeExample];exampleDialog.querySelector('pre').textContent=ex.text;document.getElementById('example-title').textContent=ex.title+'の記入例';exampleDialog.querySelector('.hint').textContent=ex.hint||'［ ］の部分を実際の内容に書き換え、当てはまらない行は削除してください。';exampleDialog.showModal();return;}if(b.dataset.go!==undefined){state.step=Number(b.dataset.go);render(true);}if(b.dataset.add){state[b.dataset.add].push({});render();}if(b.dataset.remove){state[b.dataset.remove].splice(Number(b.dataset.index),1);render();}});
document.getElementById('back').addEventListener('click',()=>{if(state.step>0){state.step--;render(true);}});document.getElementById('next').addEventListener('click',()=>{if(state.step<5){state.step++;render(true);}else{const n=document.getElementById('notice');n.textContent='確認体験が終わりました。入力内容は送信・掲載されていません。';n.hidden=false;setTimeout(()=>n.hidden=true,5000);}});document.getElementById('form').addEventListener('submit',e=>e.preventDefault());




let activeExample='selection';
const dutiesExample='仕事の概要について記載します。\n\n＜具体的には＞\n・業務内容1\n・業務内容2\n・業務内容3\n\n仕事や業務についての補足説明や\n入社後の流れ、社内でのフォロー体制などについて\n記載していきます。';
const selectionExample='【応募後の流れ】\n1. ご応募いただいた内容を確認し、担当者からご連絡します。\n2. 面接を行います。仕事の内容や働き方についてもご説明します。\n3. 選考結果をご連絡します。\n\n【面接について】\n場所：［面接場所］\n持ち物：［必要な持ち物］\n\n【入社日】\n入社日はご相談のうえ決定します。';

const examples={
 duties:{title:'仕事内容',text:dutiesExample,hint:'この構成をもとに、実際の仕事内容に書き換えてください。'},
 selection:{title:'選考について',text:selectionExample},
 required:{title:'必須の資格・経験',text:'【必須の資格】\n・［資格名］\n\n【必要な経験】\n・［仕事内容・経験の内容］\n\n資格・経験を問わない場合：\n資格・経験は問いません。',hint:'本当に必要な条件だけ書いてください。「資格・経験を問わない場合」の文章と条件の一覧は、どちらかを選んで使ってください。'},
 welcome:{title:'歓迎する資格・経験',text:'・［業務名］の経験がある方\n・［資格名］をお持ちの方\n・［仕事に役立つスキル］を活かしたい方',hint:'応募に必須ではない条件を記載します。当てはまるものだけ使ってください。'},
 holidays:{title:'休日・休暇',text:'【休日】\n［曜日・週または月の休日日数・シフトの決め方］\n\n【休暇】\n年末年始・夏季休暇・有給休暇など、実際に取得できる休暇を記載します。\n\n【補足】\n［希望休の相談方法など］'},
 benefits:{title:'待遇の補足',text:'・［福利厚生の内容・利用条件］\n・［制服・備品などの貸与内容］\n・［研修・資格取得支援の内容と条件］',hint:'実際に用意している待遇だけ記載してください。給与画面の手当や加入保険は、ここで繰り返す必要はありません。'},
 workIntro:{title:'職場紹介',text:'【どんな職場？】\n［職場の雰囲気・チームの人数や役割］\n\n【一緒に働く人】\n［仕事での連携や、相談できる相手］\n\n【働きやすさ】\n［設備・仕事の進め方など、職場の特徴］'},
 additionalText:{title:'交通費・条件付き手当',text:'【手当名】［交通費・資格手当など］\n【支給額・上限】［金額／実費支給など］\n【支給のタイミング】［毎月・勤務日ごとなど］\n【対象となる条件】［対象者・勤務条件など］',hint:'手当ごとに記載してください。全員に毎回支給する手当は「一律支給手当」の欄に入力します。'},
 windowBreak:{title:'長く働く日の勤務時間と休憩',text:'［開始時刻］～［終了時刻］で働く場合：休憩［時間・分］\nそのほかの勤務時間の場合：［休憩の決まり方］',hint:'実際に働く時間と、その場合の休憩を記載します。勤務できる時間帯全体を実働時間として書かないでください。'},
 renewalTerms:{title:'契約の更新条件',text:'【更新の判断】\n［更新を判断する条件］\n\n【確認する時期】\n［いつ更新について確認するか］',hint:'実際の契約で定めている内容を書いてください。このひな形だけで契約条件が十分かどうかを判定するものではありません。'},
 trialBasis:{title:'試用期間の決め方',text:'通常は［期間］です。\n［期間が変わる条件］の場合は、［最長の期間］までとなります。',hint:'期間に幅がある理由と、どのように期間が決まるかを実際の条件に合わせて記載してください。'},
 upperBasis:{title:'最高額になる条件',text:'［資格・経験・担当する業務など］の場合に、給与総額［金額］円となります。',hint:'実際にその給与額を支給する条件だけ書いてください。金額欄に入力した上限額と一致させてください。'}
};

const exampleDialog=document.createElement('dialog');
exampleDialog.id='selection-example';
exampleDialog.setAttribute('aria-labelledby','example-title');
exampleDialog.innerHTML='<h2 id="example-title">選考についての記入例</h2><p class="hint">実際の選考に合う部分を使ってください。面接場所・持ち物などは書き換えてください。</p><pre class="example-text"></pre><div class="dialog-actions"><button type="button" class="secondary" id="example-close">閉じる</button><button type="button" class="primary" id="example-use">この例を入力欄に入れる</button></div><p class="hint" id="replace-note" hidden>入力済みの文章を置き換えます。</p>';
document.body.append(exampleDialog);
exampleDialog.querySelector('pre').textContent=selectionExample;
document.getElementById('example-close').addEventListener('click',()=>exampleDialog.close());
exampleDialog.addEventListener('click',e=>{if(e.target===exampleDialog){const r=exampleDialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)exampleDialog.close();}});
document.getElementById('example-use').addEventListener('click',()=>{if(val(activeExample)&&!exampleDialog.dataset.confirmReplace){exampleDialog.dataset.confirmReplace='yes';document.getElementById('replace-note').hidden=false;document.getElementById('example-use').textContent='入力済みの文章を置き換える';return;}v[activeExample]=examples[activeExample].text;exampleDialog.close();render();document.getElementById(activeExample)?.focus();});
exampleDialog.addEventListener('close',()=>{delete exampleDialog.dataset.confirmReplace;document.getElementById('replace-note').hidden=true;document.getElementById('example-use').textContent='この例を入力欄に入れる';document.querySelector('[data-example="'+activeExample+'"]')?.focus();});
render();

// Adapter for this isolated converter only; original evaluated input PoCs remain untouched.
window.addEventListener('message',event=>{
 if(event.source!==window.parent||event.data?.type!=='0en-import'||!event.data.values)return;
 if(location.origin!=='null'&&event.origin!==location.origin)return;
 const allowed=new Set(['company','jobTitle','employment','duties','workplace','address','holidays','benefits','insurance','selection','companyAddress','contact','required','workIntro','timeMode','otherTime','unit','totalOnly','reported','totalFormat','reportedMax','trial','trialMin','trialUnit','trialDiff','trialSalaryDiff','trialSalaryUnit','trialBase','trialBenefitsDiff','trialBenefits','trialAllowances']);
 for(const key of Object.keys(v))delete v[key];state.allowances=[{}];state.shifts=[{}];state.examples=[{}];
 for(const [k,value] of Object.entries(event.data.values))if(allowed.has(k)&&['string','boolean'].includes(typeof value))v[k]=value;
 v.qualOpen=Boolean(v.required);v.extrasOpen=Boolean(v.workIntro||v.benefits||v.selection);state.step=0;render(true);
 event.source.postMessage({type:'0en-imported'},event.origin==='null'?'*':event.origin);
});