const escPreview=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtPreview=(v,lists)=>SeekerData.salary(v,lists);
const paramId=Number(new URLSearchParams(location.search).get('id'));
const job=SeekerData.load().find(item=>item.id===paramId);
const value=job?.revisions?.at(-1)?.values||job?.values||{};
const lists=job?.revisions?.at(-1)?.lists||job?.lists||{};
const schedule=value.timeMode==='other'?value.otherTime:value.timeMode==='fixed'?`${value.start||''}～${value.end||''}（休憩${value.break||'未入力'}分）`:value.timeMode==='window'?`勤務可能時間帯：${value.windowStart||''}～${value.windowEnd||''}`:(lists.shifts||[]).filter(s=>s.start||s.end).map(s=>`${s.start||''}～${s.end||''}（休憩${s.break??'未入力'}分）`).join('\n');
const section=(label,text)=>text?`<section class="preview-section"><h2>${escPreview(label)}</h2><p>${escPreview(text)}</p></section>`:'';
const main=document.getElementById('preview-main');
if(!job){main.innerHTML='<section class="preview-empty"><h1>プレビューできません</h1><p>保存済みの求人が見つかりません。</p></section>';}
else {main.innerHTML=`<div class="preview-ribbon">企業側で保存した最新原稿を、求職者画面の形式で表示しています。未掲載でも確認できます。</div><article class="preview-job"><p class="company">${escPreview(value.company||'募集企業未入力')}</p><h1>${escPreview(value.jobTitle||'求人タイトル未入力')}</h1><div class="tags"><span>${escPreview(SeekerData.employment[value.employment]||'雇用形態未入力')}</span><span>${escPreview(SeekerData.occupations[value.occupation]||'仕事の種類未入力')}</span></div><div class="preview-summary"><dl><dt>給与</dt><dd>${escPreview(fmtPreview(value,lists))}</dd><dt>勤務地</dt><dd>${escPreview(value.address||value.workplace||'勤務地未入力')}</dd><dt>勤務時間</dt><dd>${escPreview(schedule||'勤務時間未入力')}</dd><dt>休日</dt><dd>${escPreview(value.holidays||'休日・休暇未入力')}</dd></dl></div>${section('仕事内容',value.duties)}${section('給与',fmtPreview(value,lists)+(value.salaryNotes?'\n'+value.salaryNotes:''))}${section('勤務時間',schedule)}${section('休日・休暇',value.holidays)}${section('待遇・福利厚生',[value.insurance,value.benefits].filter(Boolean).join('\n'))}${section('試用期間',value.trial==='no'?'試用期間なし':value.trial?`${value.trialMin||'未入力'}${{month:'か月',week:'週間',day:'日'}[value.trialUnit]||''}\n${value.trialDiff==='same'?'本採用と同条件':value.trialBenefits||'条件は確認中'}`:'試用期間未入力')}${section('応募資格・対象',[value.required,value.welcome].filter(Boolean).join('\n'))}${section('勤務地・アクセス',[value.workplace,value.address].filter(Boolean).join('\n'))}<section class="preview-apply"><h2>応募について</h2><p>この画面は表示確認用です。実際の応募ボタンは、0ENへ掲載した後に表示されます。</p></section></article>`;}
