'use strict';
let extraction=null,imported=false;
const $=id=>document.getElementById(id);const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function display(value){if(typeof value!=='object')return String(value);const unit={month:'月給',hour:'時給',day:'日給',annual:'年俸'}[value.unit];return `${unit}\n総額・下限：${value.min===null?'未取得':value.min.toLocaleString('ja-JP')}円\n上限：${value.max===null?'なし（記載なし）':value.max.toLocaleString('ja-JP')+'円'}\n表記：${{exact:'単一額',range:'範囲',above:'下限のみ（以上）'}[value.format]}`;}
function showExtraction(result){extraction=result;const fields=Object.entries(extraction.fields);$('message').textContent=`取得できた項目 ${fields.filter(([,f])=>f.status==='clear').length}／確認が必要 ${fields.filter(([,f])=>f.status==='review').length}／未取得 ${fields.filter(([,f])=>f.status==='missing').length}`;$('notices').innerHTML=extraction.notices.map(n=>`<li>${html(n)}</li>`).join('');$('results').innerHTML=fields.map(([k,f])=>`<section class="card"><h2>${html(f.label)} <span class="tag ${f.status}">${{clear:'取得できました',review:'選択が必要',missing:'未取得'}[f.status]}</span></h2>${f.note?'<p class="hint">'+html(f.note)+'</p>':''}${f.candidates.length?`<label class="field"><span>反映する内容</span><select data-result="${k}"><option value="">反映しない</option>${f.candidates.map((c,i)=>`<option value="${i}" ${f.status==='clear'&&i===0?'selected':''}>候補${i+1}${c.sources.length>1?'（同一記載'+c.sources.length+'箇所）':''}</option>`).join('')}</select></label><div class="result-value" id="value-${k}">${f.status==='clear'?html(display(f.value)):'候補を選んでください'}</div><details><summary>元の記載を確認</summary>${f.candidates.map((c,i)=>`<h3>候補${i+1}</h3>${c.sources.map(s=>`<p class="hint">${html(s.label||('解析対象の'+s.start+'～'+s.end+'行'))}</p><div class="source">${html(s.text)}</div>`).join('')}`).join('')}</details>`:'<p class="hint">入力画面では空欄のままです。</p>'}</section>`).join('');$('import-actions').hidden=false;$('editor-section').hidden=true;}
function failure(e){$('message').textContent=e.message;extraction=null;$('results').innerHTML='';$('import-actions').hidden=true;}
$('convert').addEventListener('click',()=>{try{if(!$('input-text').value.trim())throw Error('原稿を貼り付けてください。');showExtraction(AirworkParser.parse($('input-text').value));}catch(e){failure(e);}});
$('results').addEventListener('change',e=>{const k=e.target.dataset.result;if(!k)return;const c=extraction.fields[k].candidates[e.target.value];$('value-'+k).textContent=c?display(c.value):'反映しません';});
$('apply').addEventListener('click',()=>{if(!extraction)return;if(imported&&!confirm('編集中の求人入力を、今回の抽出結果で置き換えますか？'))return;const selected={};document.querySelectorAll('[data-result]').forEach(s=>{if(s.value!=='')selected[s.dataset.result]=extraction.fields[s.dataset.result].candidates[Number(s.value)].value;});const values=AirworkParser.toInput(selected);$('editor-section').hidden=false;$('editor').contentWindow.postMessage({type:'0en-import',values},location.origin==='null'?'*':location.origin);imported=true;$('editor-section').scrollIntoView({behavior:'smooth'});});
window.addEventListener('message',e=>{if(e.source===$('editor').contentWindow&&e.data?.type==='0en-imported')$('message').textContent='求人入力に反映しました。未取得の条件を補い、最後の画面で原稿を確認してください。';});

let table=null;
$('read-file').addEventListener('click',async()=>{try{const file=$('source-file').files[0];if(!file)throw Error('CSVまたはTXTを選んでください。');if(file.size>5000000)throw Error('5MB以内のファイルを選んでください。');table=AirworkCSV.read(AirworkCSV.decode(await file.arrayBuffer(),$('encoding').value),$('delimiter').value);const title=table.headers.findIndex(h=>AirworkCSV.code(h)==='title');$('job-list').innerHTML=table.rows.map((r,i)=>`<option value="${i}">${i+1}. ${html(title<0?'職種名の列なし':r[title])}</option>`).join('');$('file-status').textContent=`${table.headers.length}列・${table.rows.length}求人を読み込みました。`; $('choose-job').hidden=!table.rows.length;}catch(e){table=null;$('choose-job').hidden=true;$('file-status').textContent=e.message;}});
$('convert-row').addEventListener('click',()=>{try{showExtraction(AirworkCSV.mapRow(table,Number($('job-list').value)));}catch(e){failure(e);}});
