/* Read-only XLSX adapter: no formula evaluation, network, or new Job schema. */
window.AirworkExcel=(()=>{
const nodes=(el,name)=>Array.from(el.getElementsByTagNameNS('*',name));
function xml(text){if(/<!DOCTYPE|<!ENTITY/i.test(text))throw Error('外部実体を含むExcelは読み込めません。');const d=new DOMParser().parseFromString(text,'application/xml');if(d.getElementsByTagName('parsererror').length)throw Error('ExcelのXMLが壊れています。');return d;}
async function open(buffer){const zip=await JSZip.loadAsync(buffer);let total=0;async function doc(path,optional=false){const entry=zip.file(path);if(!entry){if(optional)return null;throw Error('Excelの必要なデータがありません：'+path);}const text=await entry.async('string');total+=text.length;if(total>30000000)throw Error('Excelの展開後データが大きすぎます。');return xml(text);}
const book=await doc('xl/workbook.xml'),rels=await doc('xl/_rels/workbook.xml.rels'),strings=await doc('xl/sharedStrings.xml',true);const shared=strings?nodes(strings,'si').map(si=>nodes(si,'t').map(t=>t.textContent).join('')):[];
const relationships=new Map(nodes(rels,'Relationship').filter(r=>r.getAttribute('TargetMode')!=='External').map(r=>[r.getAttribute('Id'),r.getAttribute('Target')]));
const sheets=nodes(book,'sheet').map(s=>({name:s.getAttribute('name'),target:relationships.get(s.getAttributeNS('http://schemas.openxmlformats.org/officeDocument/2006/relationships','id'))})).filter(s=>s.target);if(!sheets.length)throw Error('読み込めるシートがありません。');
async function read(index){const sheet=sheets[index];if(!sheet)throw Error('シートを選択してください。');let path=sheet.target.startsWith('/')?sheet.target.slice(1):'xl/'+sheet.target;const parts=[];for(const segment of path.split('/')){if(segment==='..')parts.pop();else if(segment!=='.')parts.push(segment);}path=parts.join('/');if(!path.startsWith('xl/'))throw Error('未対応のシート参照です。');const d=await doc(path),rows=[],warnings=[];
for(const row of nodes(d,'row')){const values=[];for(const c of nodes(row,'c')){const ref=c.getAttribute('r');const m=ref?.match(/^([A-Z]+)\d+$/);if(!m)throw Error('セルの位置を取得できません。');let column=0;for(const char of m[1])column=column*26+char.charCodeAt(0)-64;if(column>1000)throw Error('1000列以内のExcelを使用してください。');let value='';const type=c.getAttribute('t');if(nodes(c,'f').length){warnings.push(ref+'：数式セルは反映しません');}else if(type==='s'){const i=Number(nodes(c,'v')[0]?.textContent);if(!Number.isInteger(i)||i<0||i>=shared.length)throw Error('文字列参照が不正です。');value=shared[i];}else if(type==='inlineStr')value=nodes(c,'t').map(t=>t.textContent).join('');else if(type==='e'){warnings.push(ref+'：エラーセルは反映しません');}else value=nodes(c,'v')[0]?.textContent||'';values[column-1]=value;}if(values.some(v=>v!==''))rows.push(values);if(rows.length>5001)throw Error('5000求人以内のExcelを使用してください。');}
if(!rows.length)throw Error('シートが空です。');const headers=Array.from(rows.shift(),v=>String(v??''));if(headers.some(h=>!h)||new Set(headers).size!==headers.length)throw Error('1行目の列名が空欄または重複しています。');if(rows.some(r=>r.length>headers.length))throw Error('列名より多いデータ列があります。');return {headers,rows:rows.map(r=>headers.map((_,i)=>String(r[i]??''))),warnings,sheet:sheet.name};}
return {sheets,read};}
return {open};})();
