(function(){
  if(typeof SeekerData==='undefined')return;
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const profile=()=>{try{return JSON.parse(localStorage.getItem('0en-company-profile-v03')||'{}')}catch{return {}}};
  const items=()=>SeekerData.published(SeekerData.load());
  const itemFor=id=>items().find(item=>item.id===Number(id));
  const shareFor=item=>{const v=item.values,url=location.origin+'/jobs/'+item.id,title=(v.company?v.company+'｜':'')+(v.jobTitle||'求人情報'),text=`【求人情報】\n${title}\n${SeekerData.salary(v,item.lists)}\n${v.address||''}`.trim();return {url,title,text,x:`https://twitter.com/intent/tweet?text=${encodeURIComponent(text)}&url=${encodeURIComponent(url)}`,threads:`https://www.threads.net/intent/post?text=${encodeURIComponent(text+'\n'+url)}`,facebook:`https://www.facebook.com/sharer/sharer.php?u=${encodeURIComponent(url)}`,line:`https://social-plugins.line.me/lineit/share?url=${encodeURIComponent(url)}&text=${encodeURIComponent(text)}`};};
  let active=null;
  const dialog=document.createElement('dialog');dialog.id='share-dialog';dialog.innerHTML='<button class="dialog-close" aria-label="閉じる">×</button><p class="eyebrow">求人を広める</p><h2>この求人をシェア</h2><p class="share-note">企業自身のSNSや連絡先で、この求人を知らせられます。</p><div class="share-native-box"><button class="primary share-native" type="button">共有先を選ぶ</button><p class="share-note">対応端末では、LINEなどの共有先をまとめて選べます。</p></div><div class="share-grid"><a class="share-option share-option-x" data-share-network="x" target="_blank" rel="noopener" aria-label="Xで共有"><span class="share-icon" aria-hidden="true">𝕏</span><span>X</span></a><a class="share-option share-option-threads" data-share-network="threads" target="_blank" rel="noopener" aria-label="Threadsで共有"><span class="share-icon" aria-hidden="true">＠</span><span>Threads</span></a><a class="share-option share-option-facebook" data-share-network="facebook" target="_blank" rel="noopener" aria-label="Facebookで共有"><span class="share-icon" aria-hidden="true">f</span><span>Facebook</span></a><a class="share-option share-option-line" data-share-network="line" target="_blank" rel="noopener" aria-label="LINEで共有"><span class="share-icon" aria-hidden="true">LINE</span><span>LINE</span></a></div><button class="secondary share-copy" type="button">URLをコピー</button><p class="share-status" role="status"></p><p class="share-url"></p>';document.body.append(dialog);
  const open=id=>{active=itemFor(id);if(!active)return;const data=shareFor(active);dialog.querySelector('.share-url').textContent=data.url;for(const a of dialog.querySelectorAll('[data-share-network]'))a.href=data[a.dataset.shareNetwork];dialog.querySelector('.share-status').textContent='';dialog.showModal();};
  const addButton=(holder,id,label='シェア')=>{if(!holder||holder.querySelector(`[data-share-id="${id}"]`))return;const b=document.createElement('button');b.type='button';b.className='share-trigger';b.dataset.shareId=id;b.textContent=label;holder.append(b);};
  const enhance=()=>{for(const row of document.querySelectorAll('.job-row')){const edit=row.querySelector('[data-action="edit"]');const id=edit?.dataset.job;if(id&&itemFor(id))addButton(row.querySelector('.minor-actions'),id,'共有');}for(const card of document.querySelectorAll('.job-card')){const link=card.querySelector('h3 a');const id=link?.href.match(/\/jobs\/(\d+)/)?.[1];if(id)addButton(card.querySelector('.job-conditions'),id);}
    const detail=document.querySelector('.detail-title');const detailId=location.pathname.match(/^\/jobs\/(\d+)/)?.[1];if(detail&&detailId){addButton(detail,detailId,'この求人をシェア');const v=itemFor(detailId)?.values;const url=safeWebsite(v?.companyWebsite||profile().website);if(url&&!detail.querySelector('.company-site-link')){const a=document.createElement('a');a.className='company-site-link';a.href=url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='🌐 企業Webサイトを見る';detail.append(a);}}
    const preview=document.querySelector('.preview-job');const previewUrl=safeWebsite(profile().website);if(preview&&previewUrl&&!preview.querySelector('.company-site-link')){const a=document.createElement('a');a.className='company-site-link';a.href=previewUrl;a.target='_blank';a.rel='noopener noreferrer';a.textContent='🌐 企業Webサイトを見る';preview.querySelector('h1')?.after(a);}};
  const safeWebsite=value=>{try{const u=new URL(String(value||''));return ['http:','https:'].includes(u.protocol)&&!u.username&&!u.password?u.href:''}catch{return ''}};
  document.addEventListener('click',e=>{const b=e.target.closest('[data-share-id]');if(b){e.preventDefault();open(b.dataset.shareId);}if(e.target.closest('.share-native')&&active){const data=shareFor(active);if(navigator.share)navigator.share({title:data.title,text:data.text,url:data.url}).catch(()=>{});else dialog.querySelector('.share-status').textContent='このブラウザでは端末共有に対応していません。下のSNSまたはURLコピーを使えます。';}if(e.target.closest('.share-copy')&&active){const url=shareFor(active).url;const done=()=>dialog.querySelector('.share-status').textContent='URLをコピーしました。';if(navigator.clipboard?.writeText)navigator.clipboard.writeText(url).then(done).catch(()=>fallback(url,done));else fallback(url,done);}});
  function fallback(text,done){const t=document.createElement('textarea');t.value=text;document.body.append(t);t.select();try{document.execCommand('copy');done()}finally{t.remove();}}
  dialog.querySelector('.dialog-close').onclick=()=>dialog.close();new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true});enhance();
})();
